### ISSUE TITLE
where is toucheEnd?

### ISSUE THREAD

**Issue by wzc118** [jsososo/wx-app-painting#1]
I met this error: 
VM3867:1 Do not have toucheEnd handler in current page: pages/canvas/canvas. Please make sure that toucheEnd handler has been defined in pages/canvas/canvas, or pages/canvas/canvas has been added into app.json.

**Comment by jsososo** [comment]
cause i bind a function called touchEnd in wxml but didn't define in js.  Actually bindtoucheend is not necessary and u can delete it
