### ISSUE TITLE
有关画板的功能

### ISSUE THREAD

**Issue by null-yer** [jsososo/wx-app-painting#3]
您好，最近看了您写的画板功能，我最近也在做小程序画板功能，遇到了一个问题，想请教一下，同时也发现您的画板也存在这样的问题，小程序中的touchMove这个时间的灵敏度好像不太高，如果绘画过快会导致有些触点不能触发，就会导致画圆时有明显的僵硬感，一直在研究但是没有什么思路，您可以参考一下“手绘微课”这个做的效果特别好，但是不知道怎么实现的，谢谢

**Comment by jsososo** [comment]
嗯，是的，之前有段时间想解决这个问题来着，后来又去做其他项目搁置了一下，最近我会再看下这个问题的

**Comment by jsososo** [comment]
你好，可以试下 quadraticCurveTo 这个方法，去替代 lineTo，具体代码实现的话可以参考 dev/newDraw 分支里的 utils/paint.js 文件，这个分支里现在只对第一个画画有做了改变，你可以先稍微看下
