### ISSUE TITLE
iOS下选择图片后，白屏

### ISSUE THREAD

**Issue by savokiss** [jsososo/wx-app-painting#4]
iOS下background不能设置为缓存图片，改为网络图片可以解决

**Comment by jsososo** [comment]
刚确认了下，确实存在这个问题，估计是新版本的微信引起的，明天去提个工单看看，如果不行就要再想想别的办法了

**Comment by jsososo** [comment]
官方回应仅支持网络图片了，那么在不上传到服务器的前提下，我把它改成取消掉橡皮擦，改用撤销吧

**Comment by jsososo** [comment]
新提交的版本我已经把涂照片的那一块橡皮擦改成了撤销，刚提到微信审核，相关的代码看着有一点乱，写的有点早了，我有空再整理整理

**Comment by savokiss** [comment]
awesome~ 👍
