### ISSUE TITLE
你好咨询一下，关于添加文字

### ISSUE THREAD

**Issue by cooliean** [jsososo/wx-app-painting#5]
请问文字的添加思路是什么呢，不会啊，谢谢了

**Comment by jsososo** [comment]
CanvasContext.fillText 文档上是这个api，你可以看下，我这里没有用到过，另外如果要做一些复杂的文本、绘图的话我还是并不太建议用canvas去处理，如果后端能生成最好

**Comment by cooliean** [comment]
嗯，好的，谢谢了，我研究一下
